<?php

/**
 * Implementation of hook_schema().
 */
function hosting_ndi_schema() {
  $schema['hosting_ndi'] = array(
    'fields' => array(
      'nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'ndi_civi_ext' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
      ),
    ),
  );

  return $schema;
}
