<?php


/**
 * Implementation of hook_menu().
 */
function hosting_ndi_menu() {
  $items = array();
  $items['admin/hosting/ndi_civicrm'] = array(
    'title' => 'NDI CiviCRM Extensions',
    'description' => 'Configure the CiviCRM extensions to make available to enable during site provisioning.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_ndi_settings'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer NDI CiviCRM extensions'),
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function hosting_ndi_perm() {
  return array('administer NDI CiviCRM extensions');
}

/**
 * NDI CiviCRM settings form.
 */
function hosting_ndi_settings() {

  $form['settings'] = array(
    '#type' => 'item',
    '#title' => t('NDI CiviCRM settings'),
    '#value' => t('Here you may set various configurations for NDI CiviCRM extensions.'),
    '#weight' => 0,
  );

  $form['hosting_ndi_extensions'] = array(
    '#type' => 'textarea',
    '#title' => t('NDI CiviCRM extensions'),
    '#description' => t('List the NDI CiviCRM extensions available when provisioning a site, one per line'),
    '#default_value' => implode("\n", variable_get('hosting_ndi_extensions', array())),
  );

  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );

  return $form;
}

/**
 * Submit callback.
 */
function hosting_ndi_settings_submit($form, &$form_state) {
  $extensions = explode("\n", $form_state['values']['hosting_ndi_extensions']);
  foreach ($extensions as $key => $value) {
    $value = trim($value);
    $extensions[$value] = $value;
    unset($extensions[$key]);
  }

  variable_set('hosting_ndi_extensions', $extensions);
}

/**
 * Implementation of hook_form_alter()
 */
function hosting_ndi_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $form['ndi'] = array(
      '#type' => 'fieldset',
      '#title' => t('NDI CiviCRM'),
      '#description' => t('Enable CiviCRM extensions when proivisioning a site.'),
    );

    $form['ndi']['ndi_civi_ext'] = array(
      '#type' => 'checkboxes',
      '#options' => variable_get('hosting_ndi_extensions', array()),
      '#title' => t('Extension to enable'),
//      '#default_value' => $form['#node']->ndi_civi_ext ? $form['#node']->ndi_civi_ext : '',
      '#weight' => 0,
    );

    return $form;
  }
}

/**
 * Implementation of hook_insert()
 */
function hosting_ndi_insert($node) {
  if (!empty($node->ndi_civi_ext)) {
    foreach ($node->ndi_civi_ext as $key => $value) {
      if ($value !== 0) {
        db_query("INSERT INTO {hosting_ndi} (vid, nid, ndi_civi_ext) VALUES (%d, %d, '%s')", $node->vid, $node->nid, $key);
      }
    }
  }
}

/**
 * Implementation of hook_update()
 */
function hosting_ndi_update($node) {
  if (FALSE === db_fetch_array(db_query("SELECT ndi_civi_ext FROM {hosting_ndi} WHERE vid = %d", $node->vid))) {
    hosting_ndi_insert($node);
  }
  else {
    db_query("UPDATE {hosting_ndi} SET ndi_civi_ext = '%s' WHERE vid = %d", $node->ndi_civi_ext, $node->vid);
  }

}

/**
 * Implementation of hook_delete()
 */
function hosting_ndi_delete($node) {
  db_query("DELETE FROM {hosting_ndi} WHERE nid=%d", $node->nid);
}

/**
 * Implementation of hook_delete_revision()
 */
function hosting_ndi_delete_revision($node) {
  db_query("DELETE FROM {hosting_ndi} WHERE vid=%d", $node->vid);
}

/**
 * Implementation of hook_nodeapi()
 */
function hosting_ndi_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
    case 'insert':
        hosting_ndi_insert($node);
        break;
      case 'update':
        hosting_ndi_update($node);
        break;
      case 'delete' :
        hosting_ndi_delete($node);
        break;
      case 'delete revision':
        hosting_ndi_delete_revision($node);
        break;
      case 'load':
        $result = db_query("SELECT ndi_civi_ext FROM {hosting_ndi} WHERE vid = %d", $node->vid);

        while ($row = db_fetch_object($result)) {
          $results[] = $row->ndi_civi_ext;
        }
        
        $additions = array('ndi_civi_ext' => $results);
        return $additions;
        break;
    }
  }
}
