<?php

/**
 * Implementation of hook_menu().
 */
function hosting_ndi_menu() {
  $items = array();
  $items['admin/hosting/ndi_civicrm'] = array(
    'title' => 'NDI CiviCRM Extensions',
    'description' => 'Configure the CiviCRM extensions to make available to enable during site provisioning.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_ndi_settings'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer NDI CiviCRM extensions'),
  );
  $items['admin/hosting/ndi_site_list'] = array(
    'title' => 'NDI site list',
    'description' => 'A list of all sites and their aliases (for monitoring).',
    'page callback' => 'hosting_ndi_site_list',
    'access arguments' => array('view ndi site list'),
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function hosting_ndi_permission() {
  return array(
    'administer NDI CiviCRM extensions' => array(
      'title' => t('Administer NDI CiviCRM extensions'),
      'description' => t('Perform administration tasks for NDI CiviCRM extensions.'),
    ),
    'view ndi site list' => array(
      'title' => t('View the NDI site list'),
      'description' => t('View a list of all enabled dites and their URL alises.'),
    ),
  );
}

/**
 * Callback to print a site list.
 */
function hosting_ndi_site_list() {
  $servers = hosting_get_servers('http');
  $platforms = array();
  foreach ($servers as $server_nid => $server_name) {
    $platforms += _hosting_get_platforms($server_nid);
  }
  $sites = array();
  foreach ($platforms as $platform_nid => $platform_name) {
    $sites += hosting_get_sites_by_status($platform_nid, HOSTING_SITE_ENABLED);
  }
  $urls = array();
  foreach ($sites as $site_nid => $node) {
    $site = $node->title;
    $urls[$site] = array($site);
    $urls[$site] = array_merge($urls[$site], $node->aliases);
    $urls[$site] = array_merge($urls[$site], $node->aliases_automatic);
  }
  print drupal_json_encode($urls);
}

/**
 * NDI CiviCRM settings form.
 */
function hosting_ndi_settings() {

  $form['settings'] = array(
    '#type' => 'item',
    '#title' => t('NDI CiviCRM settings'),
    '#markup' => t('Here you may set various configurations for NDI CiviCRM extensions.'),
    '#weight' => 0,
  );

  $form['hosting_ndi_extensions'] = array(
    '#type' => 'textarea',
    '#title' => t('NDI CiviCRM extensions'),
    '#description' => t('List the NDI CiviCRM extensions available when provisioning a site, one per line'),
    '#default_value' => implode("\n", variable_get('hosting_ndi_extensions', array())),
  );

  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );

  return $form;
}

/**
 * Submit callback.
 */
function hosting_ndi_settings_submit($form, &$form_state) {
  $extensions = explode("\n", $form_state['values']['hosting_ndi_extensions']);
  foreach ($extensions as $key => $value) {
    $value = trim($value);
    $extensions[$value] = $value;
    unset($extensions[$key]);
  }

  variable_set('hosting_ndi_extensions', $extensions);
}

/**
 * Implementation of hook_form_alter()
 */
function hosting_ndi_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $form['ndi'] = array(
      '#type' => 'fieldset',
      '#title' => t('NDI CiviCRM'),
      '#description' => t('Enable CiviCRM extensions when provisioning a site.'),
    );
    // TODO: Fix that we show a checkbox even when no extensions are listed.
    $form['ndi']['ndi_civi_ext'] = array(
      '#type' => 'checkboxes',
      '#disabled' => isset($form['#node']->nid) ? TRUE : FALSE,
      '#options' => variable_get('hosting_ndi_extensions', array()),
      '#title' => t('Extension to enable'),
      '#default_value' => isset($form['#node']->ndi_civi_ext) ? $form['#node']->ndi_civi_ext : array(),
      '#weight' => 0,
    );
    return $form;
  }
}

/**
 * Implementation of hook_node_insert().
 */
function hosting_ndi_node_insert($node) {
  if (!empty($node->ndi_civi_ext)) {
    foreach ($node->ndi_civi_ext as $key => $value) {
      if ($value !== 0) {
        db_query("INSERT INTO {hosting_ndi} (nid, ndi_civi_ext) VALUES (:nid, :ext)",
          array(
            ':nid' => $node->nid,
            ':ext' => $value,
          )
        );
      }
    }
  }
}

/**
 * Implementation of hook_node_update().
 */
function hosting_ndi_node_update($node) {
  hosting_ndi_node_delete($node);
  hosting_ndi_node_insert($node);
}

/**
 * Implementation of hook_node_delete().
 */
function hosting_ndi_node_delete($node) {
  db_query("DELETE FROM {hosting_ndi} WHERE nid=:nid", array(':nid' => $node->nid));
}

/**
 * Implementation of hook_node_load().
 */
function hosting_ndi_node_load($nodes) {
  foreach ($nodes as $nid => $node) {
    if ($node->type == 'site') {
      if ($result = db_query("SELECT ndi_civi_ext FROM {hosting_ndi} WHERE nid=:nid", array(':nid' => $nid))) {
        foreach ($result->fetchAll() as $extension) {
          $node->ndi_civi_ext[] = $extension->ndi_civi_ext;
        }
      }
    }
  }
}
