<?php
/**
 * @file
 * hosting_ndi_inventory.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function hosting_ndi_inventory_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_inventory_enabled'.
  $field_bases['field_inventory_enabled'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_inventory_enabled',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => '',
        1 => '',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_ndi_environment'.
  $field_bases['field_ndi_environment'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_ndi_environment',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'Production' => 'Production',
        'Testing/QA' => 'Testing/QA',
        'Development' => 'Development',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
